# Dockerfile for DNS Utils
# https://packages.debian.org/bullseys/dnsutils

FROM debian:bullseye-slim

MAINTAINER joe jasper <joe jasper@gmail.com>

RUN echo 'deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free\n\
deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free\n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free\n\
deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free\n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free\n\
deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free\n\
deb http://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free\n\
deb-src http://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free\n'\
> /etc/apt/sources.list \
&& apt-get update

RUN apt-get install -y bind9-dnsutils

# Clean up.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

